version: '3'

services:

  couchdb:
    image: couchdb:2
    ports:
      - 5984:5984
    volumes:
      - ./data:/opt/couchdb/data
      - ./conf/couchdb.ini:/opt/couchdb/etc/local.d/docker.ini
    logging:
      options:
        max-size: "1M"
        max-file: "3"
    restart: on-failure

  proxy:
    image: node:lts
    command: sh -c "npm install && npm start"
#    ports:
#      - 80:80
    volumes:
      - .:/app
    working_dir: /app

  ldap_proxy:
    image: benel/aaaforrest:1.0.0
    ports:
      - 80:80 #
    volumes:
      - ./conf/aaaforrest.json:/AAAforREST/conf/config.json:ro
    working_dir: /AAAforREST

  running_infrastructure:
    image: dadarek/wait-for-dependencies
    command: couchdb:5984
    depends_on:
      - couchdb
      - proxy
      - ldap_proxy #

  push_app:
    image: benel/couchapp
    command: push . http://cassandre_couchdb_1:5984/cassandre
    volumes:
      - ./app:/app
