version: '2'

services:

  couchdb:
    image: couchdb:3
    ports:
      - 5984:5984
    volumes:
      - ./data:/opt/couchdb/data
      - ./conf/couchdb.ini:/opt/couchdb/etc/local.d/docker.ini
    logging:
      options:
        max-size: "1M"
        max-file: "3"
    mem_limit: 29g
    restart: on-failure

  proxy:
    image: node:lts
    command: sh -c "npm install && npm start"
#    ports:
#      - 80:80
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
    - couchdb

  ldap_proxy:
    image: benel/aaaforrest:latest
    ports:
      - 80:80 #
    volumes:
      - ./conf/aaaforrest.yml:/AAAforREST/conf/config.yml:ro
    working_dir: /AAAforREST
    restart: on-failure
    depends_on:
      - proxy

  push_app:
    image: benel/couchapp
    command: push .
    environment:
      - URI=http://couchdb:5984/cassandre
    volumes:
      - ./app:/app
    depends_on:
      - couchdb
