services:

  couchdb:
    image: couchdb:3
    ports:
      - 5984:5984
    volumes:
      - ./data:/opt/couchdb/data
      - ./conf/couchdb.ini:/opt/couchdb/etc/local.d/docker.ini
    environment:
      - COUCHDB_USER
      - COUCHDB_PASSWORD
    logging:
      options:
        max-size: "1M"
        max-file: "3"
    mem_limit: 20g
    restart: on-failure

  ldap_proxy:
    image: benel/aaaforrest:latest
    ports:
      - 80:80 #
    volumes:
      - ./conf/aaaforrest.yml:/AAAforREST/conf/config.yml:ro
    working_dir: /AAAforREST
    restart: on-failure
    depends_on:
      - couchdb

  push_app:
    image: benel/couchapp
    command: pushapps ddocs/.
    environment:
      - URI=http://couchdb:5984/cassandre
    volumes:
      - ./app:/app
    depends_on:
      - couchdb
